name: Update profile metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate overview metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/overview.svg
          output_action: commit
          committer_branch: output
          committer_message: "chore: update overview metrics"
          token: ${{ secrets.GITHUB_TOKEN }}
          user: petrakol
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Prague

      - name: Generate language metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/languages.svg
          output_action: commit
          committer_branch: output
          committer_message: "chore: update language metrics"
          token: ${{ secrets.GITHUB_TOKEN }}
          user: petrakol
          template: classic
          base: repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          config_timezone: Europe/Prague

      - name: Generate streak metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/streak.svg
          output_action: commit
          committer_branch: output
          committer_message: "chore: update streak metrics"
          token: ${{ secrets.GITHUB_TOKEN }}
          user: petrakol
          template: classic
          base: metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Prague

      - name: Generate contribution metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/contributions.svg
          output_action: commit
          committer_branch: output
          committer_message: "chore: update contribution metrics"
          token: ${{ secrets.GITHUB_TOKEN }}
          user: petrakol
          template: classic
          base: activity, metadata
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_visibility: all
          plugin_activity_days: 14
          plugin_activity_filter: all
          config_timezone: Europe/Prague
